version: '3'
services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./init-psql.sh:/docker-entrypoint-initdb.d/init-psql.sh
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  gems:
  database: